// @vitest-environment jsdom
import React from 'react';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {MemoryRouter,Route,Routes} from 'react-router-dom';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {Assets} from './Assets';import {AssetDetail} from './AssetDetail';import AssetForm from '../components/AssetForm';import FindingForm from '../components/FindingForm';import {api} from '../lib/api';

vi.mock('../lib/api',()=>({api:{getAssets:vi.fn(),getAsset:vi.fn(),getAssetOwners:vi.fn(),createAsset:vi.fn(),updateAsset:vi.fn(),activateAsset:vi.fn(),deactivateAsset:vi.fn()}}));
vi.mock('../contexts/TenancyContext',()=>({useTenancy:()=>({currentWorkspace:{id:'workspace-1',name:'Workspace Alpha',role_key:'application_security_engineer'}})}));
vi.mock('../layouts/DashboardLayout',()=>({default:({children})=><main>{children}</main>}));
vi.mock('../components/SectionHeader',()=>({default:({title,description,actions})=><header><h1>{title}</h1><p>{description}</p>{actions}</header>}));
vi.mock('../components/Panel',()=>({default:({title,hint,actions,children})=><section><h2>{title}</h2><p>{hint}</p>{actions}{children}</section>}));

const asset=(overrides={})=>({id:'asset-1',workspace_id:'workspace-1',organization_id:'org-1',name:'Public API',asset_type:'domain',canonical_identifier:'api.example.com',normalized_identifier:'api.example.com',environment:'production',criticality:'critical',owner:null,description:'Public production API',source:'manual',external_id:null,is_active:true,first_seen_at:'2026-07-19T00:00:00Z',last_seen_at:'2026-07-19T00:00:00Z',metadata_json:{region:'ap-south-1'},tags:['internet-facing'],related_findings_count:1,related_findings:[{id:'finding-1',title:'SQL injection',severity:'high',status:'open',updated_at:'2026-07-19T00:00:00Z'}],version:1,created_at:'2026-07-19T00:00:00Z',updated_at:'2026-07-19T00:00:00Z',...overrides});

describe('Asset inventory workflows',()=>{afterEach(cleanup);beforeEach(()=>{vi.clearAllMocks();api.getAssets.mockResolvedValue({items:[asset()],page:1,page_size:25,total:1,pages:1});api.getAssetOwners.mockResolvedValue([]);api.getAsset.mockResolvedValue(asset());api.createAsset.mockResolvedValue(asset());api.updateAsset.mockResolvedValue(asset({version:2}));api.deactivateAsset.mockResolvedValue(asset({is_active:false,version:2}));});
it('loads live assets and applies inventory filters',async()=>{render(<MemoryRouter><Assets/></MemoryRouter>);expect(await screen.findByText('Public API')).toBeTruthy();fireEvent.change(screen.getByLabelText('Type'),{target:{value:'domain'}});await waitFor(()=>expect(api.getAssets).toHaveBeenLastCalledWith('workspace-1',expect.objectContaining({asset_type:'domain',page_size:25})));});
it('renders the empty state and API errors',async()=>{api.getAssets.mockResolvedValue({items:[],page:1,page_size:25,total:0,pages:0});render(<MemoryRouter><Assets/></MemoryRouter>);expect(await screen.findByText('No assets yet')).toBeTruthy();cleanup();api.getAssets.mockRejectedValue({message:'Permission denied',status:403});render(<MemoryRouter><Assets/></MemoryRouter>);expect((await screen.findByRole('alert')).textContent).toContain('Permission denied');});
it('validates metadata and submits creation inputs',()=>{const submit=vi.fn();render(<AssetForm owners={[]} canManage onSubmit={submit}/>);fireEvent.change(screen.getByLabelText('Name'),{target:{value:'Production API'}});fireEvent.change(screen.getByLabelText(/^Canonical identifier/),{target:{value:'EXAMPLE.COM.'}});fireEvent.change(screen.getByLabelText('Tags'),{target:{value:'internet-facing, tier-1'}});fireEvent.change(screen.getByLabelText(/^Metadata JSON/),{target:{value:'not-json'}});fireEvent.click(screen.getByRole('button',{name:'Create asset'}));expect(screen.getByRole('alert').textContent).toContain('valid JSON object');fireEvent.change(screen.getByLabelText(/^Metadata JSON/),{target:{value:'{"region":"ap-south-1"}'}});fireEvent.click(screen.getByRole('button',{name:'Create asset'}));expect(submit).toHaveBeenCalledWith(expect.objectContaining({name:'Production API',asset_type:'domain',tags:['internet-facing','tier-1'],metadata_json:{region:'ap-south-1'}}));});
it('renders detail, related findings, metadata, and deactivates',async()=>{render(<MemoryRouter initialEntries={['/assets/asset-1']}><Routes><Route path="/assets/:assetId" element={<AssetDetail/>}/></Routes></MemoryRouter>);expect(await screen.findByText('SQL injection')).toBeTruthy();expect(screen.getByText('ap-south-1')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Deactivate asset'}));await waitFor(()=>expect(api.deactivateAsset).toHaveBeenCalledWith('workspace-1','asset-1',1));});
it('shows conflict state during editing',async()=>{api.updateAsset.mockRejectedValue({message:'Asset changed since it was loaded',status:409});render(<MemoryRouter initialEntries={['/assets/asset-1']}><Routes><Route path="/assets/:assetId" element={<AssetDetail/>}/></Routes></MemoryRouter>);await screen.findByText('Public production API');fireEvent.click(screen.getByRole('button',{name:'Edit'}));fireEvent.click(screen.getByRole('button',{name:'Save asset'}));expect((await screen.findByRole('alert')).textContent).toContain('Asset changed');});
it('submits a Finding asset selection',()=>{const submit=vi.fn();render(<FindingForm assets={[asset()]} onSubmit={submit}/>);fireEvent.change(screen.getByLabelText('Title'),{target:{value:'Repository secret exposure'}});fireEvent.change(screen.getByLabelText('Description'),{target:{value:'Secret material is exposed in repository history.'}});fireEvent.change(screen.getByLabelText('Asset'),{target:{value:'asset-1'}});fireEvent.click(screen.getByRole('button',{name:'Save finding'}));expect(submit).toHaveBeenCalledWith(expect.objectContaining({asset_id:'asset-1'}));});
});
