import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import DashboardLayout from '../layouts/DashboardLayout';
import Panel from '../components/Panel';
import SectionHeader from '../components/SectionHeader';
import LoadingState from '../components/LoadingState';
import { useTenancy } from '../contexts/TenancyContext';
import { api } from '../lib/api';

const slugify = value => value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const formatDate = value => new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));

const Onboarding = () => {
  const { createOrganization } = useTenancy();
  const [organizationName,setOrganizationName] = useState(''); const [workspaceName,setWorkspaceName] = useState(''); const [pending,setPending] = useState(false); const [error,setError] = useState(null);
  const submit = async event => { event.preventDefault(); setPending(true); setError(null); try { await createOrganization({name:organizationName,slug:slugify(organizationName),workspace_name:workspaceName,workspace_slug:slugify(workspaceName)}); } catch (e) { setError(e); } finally { setPending(false); } };
  return <Panel title="Establish your tenant boundary" hint="Create the organization and first workspace atomically. Your account becomes its administrator." className="gradient-border"><form onSubmit={submit} className="stack"><div className="content-grid" style={{margin:0}}><label className="field">Organization name<input className="input" required minLength={2} maxLength={120} value={organizationName} onChange={e=>setOrganizationName(e.target.value)} placeholder="Example Company" /></label><label className="field">First workspace<input className="input" required minLength={2} maxLength={120} value={workspaceName} onChange={e=>setWorkspaceName(e.target.value)} placeholder="Product Security" /></label></div>{error&&<div className="notice notice-error" role="alert">{error.message}{error.correlationId&&<span className="mono"> · {error.correlationId}</span>}</div>}<div><button className="btn btn-primary" disabled={pending}>{pending?'Creating workspace…':'Create secure workspace'}</button></div></form></Panel>;
};

export const Dashboard = () => {
  const { organizations,currentOrganization,currentWorkspace,loading:tenantLoading,error:tenantError,refresh } = useTenancy();
  const [data,setData] = useState({integrations:[],teams:[],audit:[]}); const [loading,setLoading] = useState(false); const [partialErrors,setPartialErrors] = useState([]);
  useEffect(()=>{ let active=true; if(!currentWorkspace){setData({integrations:[],teams:[],audit:[]});return;} setLoading(true); Promise.allSettled([api.getIntegrations(currentWorkspace.id),api.getTeams(currentWorkspace.id),api.getAuditEvents(currentWorkspace.id,6)]).then(results=>{if(!active)return; const keys=['integrations','teams','audit']; const next={integrations:[],teams:[],audit:[]}; const errors=[]; results.forEach((result,i)=>{if(result.status==='fulfilled')next[keys[i]]=result.value;else errors.push(result.reason);}); setData(next);setPartialErrors(errors);setLoading(false);}); return()=>{active=false};},[currentWorkspace?.id]);
  if(tenantLoading) return <DashboardLayout><LoadingState message="Loading workspace context…" /></DashboardLayout>;
  if(tenantError) return <DashboardLayout><SectionHeader title="Workspace unavailable" description="ThreatStream could not load your authorized tenant context." /><div className="notice notice-error" role="alert"><strong>{tenantError.message}</strong>{tenantError.correlationId&&<div className="mono">Correlation: {tenantError.correlationId}</div>}<button className="btn btn-secondary" onClick={refresh} style={{marginTop:12}}>Retry</button></div></DashboardLayout>;
  if(organizations.length===0) return <DashboardLayout><SectionHeader title="Create your ThreatStream workspace" description="Start with a governed tenant boundary before connecting security providers." eyebrow="Onboarding" /><Onboarding /></DashboardLayout>;
  const configured=data.integrations.filter(item=>item.configured); const healthy=configured.filter(item=>item.status==='connected');
  return <DashboardLayout><SectionHeader title="Operational overview" description={`Live state for ${currentWorkspace?.name || 'your selected workspace'}. Empty values reflect the current backend—no synthetic telemetry.`} actions={<Link className="btn btn-primary" to="/settings/integrations">Manage integrations</Link>} />
    {partialErrors.length>0&&<div className="notice notice-info" style={{marginBottom:16}}>Some sections are hidden because your role does not include their read permission, or the service is temporarily unavailable.</div>}
    {loading?<LoadingState message="Loading live workspace state…" />:<>
      <div className="metric-grid"><article className="panel metric gradient-border"><div className="metric__label">Active workspace</div><div className="metric__value" style={{fontSize:22}}>{currentWorkspace?.name}</div><div className="metric__note">{currentOrganization?.name} · {currentWorkspace?.role_key?.replaceAll('_',' ')}</div></article><article className="panel metric"><div className="metric__label">Configured integrations</div><div className="metric__value">{configured.length}</div><div className="metric__note">{healthy.length} tested connected</div></article><article className="panel metric"><div className="metric__label">Workspace teams</div><div className="metric__value">{data.teams.length}</div><div className="metric__note">Persisted team boundaries</div></article><article className="panel metric"><div className="metric__label">Recent audit events</div><div className="metric__value">{data.audit.length}</div><div className="metric__note">Latest authorized results</div></article></div>
      <div className="content-grid"><Panel title="Integration posture" hint="Provider configuration and last known safe status from the backend.">{data.integrations.length?<div className="data-list">{data.integrations.map(item=><div className="data-row" key={item.provider}><div><h3>{item.display_name}</h3><p>{item.masked_hint ? `Credential ${item.masked_hint}` : 'No credential stored'}</p></div><span className={`badge ${item.status==='connected'?'badge-success':item.configured?'badge-warning':'badge-muted'}`}>{item.status.replaceAll('_',' ')}</span></div>)}</div>:<p className="muted">No supported providers were returned for this workspace.</p>}</Panel><Panel title="Workspace control" hint="Current authorization scope used for every request."><div className="stack"><div className="data-row"><div><h3>Organization</h3><p>{currentOrganization?.name}</p></div><span className="badge badge-info">Scoped</span></div><div className="data-row"><div><h3>Workspace role</h3><p>{currentWorkspace?.role_key?.replaceAll('_',' ')}</p></div><span className="badge badge-success">Active</span></div></div></Panel></div>
      <Panel title="Recent activity" hint="Append-only workspace audit events. Secret values and encrypted payloads are never shown." style={{marginTop:16}}>{data.audit.length?<div className="data-list">{data.audit.map(event=><div className="data-row" key={event.id}><div><h3>{event.action.replaceAll('.',' · ')}</h3><p>{event.actor_email||'System actor'} · {event.target_type}</p></div><div style={{textAlign:'right'}}><span className={`badge ${event.result==='success'?'badge-success':'badge-danger'}`}>{event.result}</span><p className="mono" style={{marginTop:5}}>{formatDate(event.created_at)}</p></div></div>)}</div>:<p className="muted">No audit events are available for this workspace.</p>}</Panel>
    </>}</DashboardLayout>;
};
export default Dashboard;
