import React, { useState } from 'react';
import DashboardLayout from '../layouts/DashboardLayout';
import SectionHeader from '../components/SectionHeader';
import MetricCard from '../components/MetricCard';
import Panel from '../components/Panel';
import DataTable from '../components/DataTable';
import StatusBadge from '../components/StatusBadge';
import SearchBar from '../components/SearchBar';

export const Reports = () => {
  const [searchTerm, setSearchTerm] = useState('');

  const reportsList = [
    { name: 'Monthly Executive Threat Summary - June 2026', type: 'Executive Report', author: 'Admin Vimal', date: '2026-07-01', format: 'PDF' },
    { name: 'PCI-DSS Compliance Assessment Status', type: 'Compliance', author: 'Alex Chen', date: '2026-06-28', format: 'Excel' },
    { name: 'Vulnerability Scan Summary and Patches Ledger', type: 'Technical Scan', author: 'SecOps Scanner', date: '2026-06-25', format: 'PDF' },
    { name: 'External Network Penetration Test Findings', type: 'Penetration Test', author: 'Mandiant Team', date: '2026-06-15', format: 'PDF' },
    { name: 'Active Directory Permissions Audit Log', type: 'Access Audit', author: 'Alex Chen', date: '2026-06-10', format: 'CSV' },
    { name: 'Incident Timeline Report: INC-2026-003', type: 'Incident Summary', author: 'Jane Doe', date: '2026-07-04', format: 'PDF' }
  ];

  const filteredReports = reportsList.filter(item => 
    item.name.toLowerCase().includes(searchTerm.toLowerCase()) || 
    item.type.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const columns = [
    { header: 'Report Name', accessor: 'name', renderCell: (val) => <span style={{ fontWeight: 600 }}>{val}</span> },
    { header: 'Classification', accessor: 'type' },
    { header: 'Generated By', accessor: 'author' },
    { header: 'Date Generated', accessor: 'date' },
    {
      header: 'File Format',
      accessor: 'format',
      renderCell: (val) => {
        let status = 'info';
        if (val === 'PDF') status = 'critical'; // Red-ish badge for pdf
        else if (val === 'Excel') status = 'low'; // Green-ish badge for excel
        else if (val === 'CSV') status = 'medium'; // Yellow badge for CSV
        return <StatusBadge status={status} text={val} />;
      }
    },
    {
      header: 'Action',
      accessor: 'name',
      renderCell: (val) => (
        <a 
          href="#download" 
          onClick={(e) => { e.preventDefault(); alert(`Downloading report: ${val}`); }}
          style={{ color: 'var(--color-blue)', fontWeight: 600, textDecoration: 'none' }}
        >
          Download
        </a>
      )
    }
  ];

  return (
    <DashboardLayout>
      <SectionHeader 
        title="Security Compliance Reports" 
        description="Access monthly security summaries, automated scanning outputs, and compliance checklists."
      />

      <div style={{ display: 'flex', gap: '16px', marginBottom: '24px', flexWrap: 'wrap' }}>
        <MetricCard title="Total Saved Reports" value="124 files" status="info" subtitle="Retained in cloud vault" />
        <MetricCard title="Scheduled Exports" value="8 active" status="low" subtitle="Run automatically weekly" />
        <MetricCard title="Shared Downloads" value="288 hits" status="low" subtitle="By security managers" />
        <MetricCard title="Compliance Score" value="98.2%" status="low" subtitle="PCI-DSS / ISO27001 target" />
      </div>

      <Panel title="Saved Report Log">
        <div style={{ marginBottom: '16px', display: 'flex', justifyContent: 'flex-start' }}>
          <SearchBar value={searchTerm} onChange={setSearchTerm} placeholder="Filter reports by title or type..." style={{ maxWidth: '360px' }} />
        </div>

        <DataTable columns={columns} data={filteredReports} />
      </Panel>
    </DashboardLayout>
  );
};

export default Reports;
