/**
 * src/pages/Reports.jsx
 * Real compliance reports from Supabase `reports` table.
 */
import React, { useState, useCallback } from 'react';
import DashboardLayout from '../layouts/DashboardLayout';
import SectionHeader from '../components/SectionHeader';
import MetricCard from '../components/MetricCard';
import Panel from '../components/Panel';
import DataTable from '../components/DataTable';
import StatusBadge from '../components/StatusBadge';
import SearchBar from '../components/SearchBar';
import LoadingState from '../components/LoadingState';
import EmptyState from '../components/EmptyState';
import { supabase } from '../lib/supabase/client';
import { useApi } from '../hooks/useApi';

const FORMAT_STATUS = { PDF: 'critical', Excel: 'low', CSV: 'medium', JSON: 'info', HTML: 'high' };

export const Reports = () => {
  const [searchTerm, setSearchTerm] = useState('');

  const fetchReports = useCallback(async () => {
    const { data, error, count } = await supabase
      .from('reports')
      .select('id,name,classification,author,date_generated,file_format,created_at', { count: 'exact' })
      .order('date_generated', { ascending: false })
      .limit(100);
    if (error) throw error;
    return { rows: data || [], total: count || 0 };
  }, []);

  const { data, loading, error, refresh } = useApi(fetchReports, []);
  const rows  = data?.rows  || [];
  const total = data?.total || 0;

  const filtered = rows.filter(r => {
    const q = searchTerm.toLowerCase();
    return !q || [r.name, r.classification, r.author]
      .some(v => String(v || '').toLowerCase().includes(q));
  });

  const pdfCount        = rows.filter(r => r.file_format === 'PDF').length;
  const thisMonthCount  = rows.filter(r => {
    const d = new Date(r.date_generated || r.created_at);
    const now = new Date();
    return d.getMonth() === now.getMonth() && d.getFullYear() === now.getFullYear();
  }).length;

  const columns = [
    {
      header: 'Report Name',
      accessor: 'name',
      renderCell: val => <span style={{ fontWeight: 600 }}>{val || '—'}</span>
    },
    {
      header: 'Classification',
      accessor: 'classification',
      renderCell: val => <span style={{ color: 'var(--text-secondary)' }}>{val || '—'}</span>
    },
    {
      header: 'Generated By',
      accessor: 'author',
      renderCell: val => <span>{val || '—'}</span>
    },
    {
      header: 'Date',
      accessor: 'date_generated',
      renderCell: val => (
        <span style={{ fontFamily: 'monospace', fontSize: '11px', color: 'var(--text-secondary)' }}>
          {val || '—'}
        </span>
      )
    },
    {
      header: 'Format',
      accessor: 'file_format',
      renderCell: val => val ? <StatusBadge status={FORMAT_STATUS[val] || 'info'} text={val} /> : '—'
    },
  ];

  return (
    <DashboardLayout>
      <SectionHeader
        title="Security Compliance Reports"
        description="Access security summaries, automated scanning outputs, and compliance checklists."
        actions={
          <button
            onClick={refresh}
            style={{ backgroundColor: 'var(--panel-bg)', border: '1px solid var(--border-color)', color: 'var(--text-secondary)', borderRadius: '6px', padding: '7px 14px', fontSize: '12px', cursor: 'pointer', fontFamily: 'Inter, sans-serif' }}
          >
            ↻ Refresh
          </button>
        }
      />

      <div style={{ display: 'flex', gap: '16px', marginBottom: '24px', flexWrap: 'wrap' }}>
        <MetricCard title="Total Reports" value={total.toLocaleString()} status="info" subtitle="In report archive" />
        <MetricCard title="This Month" value={thisMonthCount} status="low" subtitle="Generated this month" />
        <MetricCard title="PDF Reports" value={pdfCount} status="info" subtitle="PDF format reports" />
        <MetricCard title="Other Formats" value={total - pdfCount} status="info" subtitle="Excel, CSV, JSON…" />
      </div>

      <Panel title="Saved Report Archive">
        <div style={{ marginBottom: '16px', display: 'flex', justifyContent: 'flex-start' }}>
          <SearchBar
            value={searchTerm}
            onChange={setSearchTerm}
            placeholder="Search by title, classification, or author…"
            style={{ maxWidth: '400px' }}
          />
        </div>

        {loading ? (
          <LoadingState message="Loading reports…" />
        ) : error ? (
          <EmptyState
            icon="⚠️"
            title="Failed to load reports"
            description={error}
            action={<button onClick={refresh} style={{ color: 'var(--color-blue)', background: 'none', border: 'none', cursor: 'pointer', fontWeight: 600 }}>Retry</button>}
          />
        ) : (
          <DataTable
            columns={columns}
            data={filtered}
            emptyText={
              searchTerm
                ? "No reports match your search."
                : "No reports generated yet. Run scans or incidents to generate compliance reports."
            }
          />
        )}
      </Panel>
    </DashboardLayout>
  );
};

export default Reports;
